export type EnrollmentDraft = {
  schoolId: string;
  schoolYear: string;
  schoolToEnroll: string;
  studentType: string;
  learnerCategory: string;
  previousSchool: string;
  previousSchoolYear: string;
  lastGradeLevel: string;
  gradeToEnroll: string;
  track: string;
  strand: string;
  semester: string;
  birthCertificateNo: string;
  lrn: string;
  email: string;
  lastName: string;
  firstName: string;
  middleName: string;
  extensionName: string;
  birthDate: string;
  gender: string;
  placeOfBirth: string;
  learnerContact: string;
  motherTongue: string;
  religion: string;
  is4Ps: string;
  fourPsHouseholdId: string;
  currentAddress: string;
  permanentAddress: string;
  fatherName: string;
  fatherContact: string;
  motherName: string;
  motherContact: string;
  guardianName: string;
  guardianContact: string;
  hasSpedNeed: string;
  preferredModality: string;
  deviceAccess: string;
  hasInternet: string;
  consent: boolean;
};

export type PublicEnrollmentSubmission = {
  id: string;
  submission_reference_id?: string | null;
  created_at: string;
  school_id: string | null;
  school_year: string | null;
  lrn: string | null;
  email: string | null;
  last_name: string | null;
  first_name: string | null;
  middle_name: string | null;
  grade_to_enroll: string | null;
  guardian_contact: string | null;
  payload: EnrollmentDraft;
};
