import type { AddressFields, GuardianFields, PublicEnrollmentResponse } from './types';

export const emptyAddress: AddressFields = {
  province: '',
  city: '',
  barangay: '',
  houseNo: '',
  street: '',
  zipCode: '',
};

export const emptyGuardian: GuardianFields = {
  lastName: '',
  firstName: '',
  middleName: '',
  contactNumber: '',
};

export const initialPublicEnrollmentForm: PublicEnrollmentResponse = {
  id: '',
  submittedAt: '',
  schoolYear: '2025-2026',
  enrollmentType: 'New Student',
  learnerClassification: 'Regular',
  schoolSource: '',
  previousSchool: '',
  lastSchoolYearAttended: '',
  lastGradeLevelAttended: '',
  gradeLevelToEnroll: 'Grade 7',
  track: '',
  strand: '',
  semester: '',
  psaBirthCertificateNo: '',
  lrn: '',
  lastName: '',
  firstName: '',
  middleName: '',
  extensionName: '',
  birthDate: '',
  gender: '',
  placeOfBirth: '',
  isIpCommunity: 'NO',
  ipCommunityName: '',
  motherTongue: '',
  religion: '',
  is4psBeneficiary: 'NO',
  household4psId: '',
  currentAddress: emptyAddress,
  permanentAddress: emptyAddress,
  samePermanentAddress: 'YES',
  father: emptyGuardian,
  mother: emptyGuardian,
  guardian: emptyGuardian,
  hasSpecialNeeds: 'NO',
  specialNeedsDiagnosis: '',
  specialNeedsManifestation: '',
  hasPwdId: 'NO',
  preferredLearningModality: '',
  preferredDevice: '',
  isDeviceShared: 'NO',
  hasInternetConnection: 'NO',
  consentAccepted: false,
};
